Pet_Project/myblog/blog/urls.py
from django.urls import path  
from . import views  
  
app_name = 'blog'  
  
urlpatterns = [    
    path('', views.post_list, name='post_list'), 
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'), 
    path('search/', views.post_search, name='post_search'),
]

Pet_Project/myblog/myblog/urls.py
from django.urls import path, include  
from django.contrib import admin  
  
  
urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('blog/', include('blog.urls', namespace='blog')), 
    path('user/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls')), 
]

Pet_Project/myblog/blog/models.py
from django.db import models 
from django.utils import timezone 
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):  
    def get_queryset(self):  
        return super(PublishedManager,self).get_queryset().filter(status='published')

class Post(models.Model): 
    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'),) 
    title = models.CharField(max_length=250) 
    slug = models.SlugField(max_length=250, unique_for_date='publish') 
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts') 
    body = models.TextField() 
    publish = models.DateTimeField(default=timezone.now) 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft') 
    objects = models.Manager()    
    published = PublishedManager()
    tags = TaggableManager()

    class Meta: 
        ordering = ('-publish',) 

    def __str__(self): 
        return self.title
    
    def get_absolute_url(self):  
        return reverse('blog:post_detail',  
		       args=[self.publish.year,  
		       self.publish.month,  
		       self.publish.day,  
		       self.slug])
    
class Comment(models.Model):  
    post = models.ForeignKey(Post,  
			     on_delete=models.CASCADE,  
			     related_name='comments')  
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE, related_name='users')
    body = models.TextField()  
    created = models.DateTimeField(auto_now_add=True)  
    updated = models.DateTimeField(auto_now=True)  
    active = models.BooleanField(default=True)  
      
    class Meta:  
        ordering = ('created',)  
          
    def __str__(self):  
        return 'Comment by {} on {}'.format(self.user, self.post)

Pet_Project/myblog/blog/forms.py
from django import forms  
from .models import Comment
  
  
class EmailPostForm(forms.Form):  
    name = forms.CharField(max_length=25)  
    email = forms.EmailField()  
    to = forms.EmailField()  
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):  
    class Meta:  
        model = Comment  
        fields = ('body',)
        labels = {
            'body': '',
        }
class SearchForm(forms.Form): 
    query = forms.CharField()

Pet_Project/myblog/blog/views.py
from django.shortcuts import redirect, render, get_object_or_404 
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count  
from django.core.mail import send_mail 
from .forms import EmailPostForm, CommentForm, SearchForm 
from .models import Post, Comment
from taggit.models import Tag 
from django.contrib.postgres.search import SearchVector 

def post_list(request, tag_slug=None):  
    object_list = Post.published.all()  
    tag = None  
  
    if tag_slug:  
        tag = get_object_or_404(Tag, slug=tag_slug)  
        object_list = object_list.filter(tags__in=[tag])  
  
    paginator = Paginator(object_list, 4)  # 3 поста на каждой странице  
    page = request.GET.get('page')  
    try:  
        posts = paginator.page(page)  
    except PageNotAnInteger:  
        # Если страница не является целым числом, поставим первую страницу  
        posts = paginator.page(1)  
    except EmptyPage:  
        # Если страница больше максимальной, доставить последнюю страницу результатов  
        posts = paginator.page(paginator.num_pages)  
    return render(request,'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})

def post_detail(request, year, month, day, post):  
    post = get_object_or_404(Post, slug=post,  
				   status='published',  
				   publish__year=year,  
				   publish__month=month,  
				   publish__day=day)  
      
    # Список активных комментариев к этой записи  
    comments = post.comments.filter(active=True)  
    new_comment = None  
    if request.method == 'POST':
        # Комментарий был опубликован
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            # Создайте объект Comment, но пока не сохраняйте в базу данных
            new_comment = comment_form.save(commit=False)
            # Назначить текущий пост комментарию
            new_comment.post = post
            new_comment.user = request.user
             # Сохранить комментарий в базе данных
            new_comment.save()
            return redirect(request.path)
    else:  
        comment_form = CommentForm() 
    post_tags_ids = post.tags.values_list('id', flat=True)  
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)  
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4] 
    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form, 'similar_posts': similar_posts})

def post_share(request, post_id):   
    # Получить пост по id   
    post = get_object_or_404(Post, id=post_id, status='published')   
    sent = False   
    if request.method == 'POST':   
        # Форма была отправлена   
        form = EmailPostForm(request.POST)   
        if form.is_valid():
            # Поля формы прошли проверку
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading " {}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True     
    else:   
        form = EmailPostForm()   
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

def post_search(request): 
    form = SearchForm() 
    query = None 
    results = [] 
    if 'query' in request.GET: 
        form = SearchForm(request.GET) 
        if form.is_valid(): 
            query = form.cleaned_data['query'] 
            results = Post.objects.annotate(
                search=SearchVector('title', 'body'), 
            ).filter(search=query) 
    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})

Pet_Project/myblog/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}  
  
{% block title %}{{ post.title }}{% endblock %}  
  
{% block content %}  
  
<h1>{{ post.title }}</h1>  
  
<p class="date">  
    Публикация {{ post.publish }}  
</p>  
{{ post.body|linebreaks }}
<p>
  <a href="{% url 'blog:post_share' post.id %}">
    Поделиться постом
</a>
</p>
<h2>Посты из этой рубрики</h2>  
{% for post in similar_posts %}  
  <p>  
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>  
  </p>
{% empty %}  
   Больше нет постов в этой рубрике.  
{% endfor %}

{% with comments.count as total_comments %}  
  <h2>  
     Колличество коментариев  {{ total_comments }} 
  </h2>  
  {% for comment in comments %}  
  <div class="comment">  
    <p class="info">  
      Комментарий {{ forloop.counter }} от {{ comment.user }}  
      {{ comment.created }}  
    </p>  
  {{ comment.body|linebreaks }}  
  </div>
  {% empty %}  
    <p>Пока нет комментариев.</p>  
  {% endfor %}
  {% if new_comment %}   
  {% else %}
  {% if user.is_authenticated %} 
  <h2>Добавить новый комментарий</h2>  
  <form action="." method="post"> 
    <div class="mb-3">
      <label for="exampleFormControlTextarea1" class="form-label">Текст комментария</label>
      <textarea class="form-control" id="exampleFormControlTextarea1" name="body" cols="40" rows="10" required id="id_body"></textarea>
    </div>
    {% csrf_token %}  
    <input type="submit" value="Отправить" class="btn btn-outline-success">  
  </form>
  {% endif %}
{% endif %}
{% endwith %}
{% endblock %}

Pet_Project/myblog/blog/templates/blog/post/latest_posts.html
{% for post in latest_posts %}
<div class="list-group">
    <a href="{{ post.get_absolute_url }}" class="list-group-item list-group-item-action">{{ post.title }}</a>
</div>
{% endfor %}

Pet_Project/myblog/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}  
  
{% block title %}My Blog{% endblock %}  
  
{% block content %}  

{% if tag %}  
<h2>{{ tag.name }}</h2>  
{% endif %}

{% for post in posts %}   
<h2>    
{{ post.title }}   
</h2>

<p class="tags">  
    Рубрика:  
    {% for tag in post.tags.all %}  
    <a href="{% url "blog:post_list_by_tag" tag.slug %}">  
        {{ tag.name }}  
    </a>  
    {% if not forloop.last %}, {% endif %}  
    {% endfor %}  
</p>

<p class="date">  
    Публикация {{ post.publish }} 
</p>  
{{ post.body|truncatewords:30|linebreaks }}  

<a href="{{ post.get_absolute_url }}">Читать полностью</a>
{% endfor %} 

{% include "../pagination.html" with page=posts %}
{% endblock %}

Pet_Project/myblog/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %}Search{% endblock %}

{% block content %}
  {% if query %}
    <h1>Посты содержащие: "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
	    Найден {{ total_results }} результат{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
      {{ post.body|truncatewords:5 }}
    {% empty %}
      <p>Ничего не найдено.</p>
    {% endfor %}
    <p><a href="{% url "blog:post_search" %}">Искать еще</a></p>
  {% else %}
    <h1>Поиск</h1>
    <form action="." method="get">
      <div class="mb-3">
        <label for="id_query" class="form-label">Введите слово для поиска:</label>
        <input type="text" class="form-control" name="query" required id="id_query">
      </div>
      <input type="submit" value="Искать" class="btn btn-outline-success">  
    </form>
  {% endif %}
{% endblock %}

Pet_Project/myblog/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}  
  
{% block title %}Share a post{% endblock %}  
  
{% block content %}  
  {% if sent %}  
    <h1>E-mail успешно отправлен</h1>  
    <p>  
      Пост "{{ post.title }}" успешно отправлен   {{ form.cleaned_data.to }}.<br>  
      <a href="{% url 'blog:post_list' %}">На главную</a>
    </p>  
  {% else %}  
    <h1>Отправить"{{ post.title }}" на e-mail</h1>  
    <form action="." method="post"> 
      <div class="mb-3">
        <label for="id_name" class="form-label">Имя:</label>
        <input type="text"  class="form-control" name="name" maxlength="25" required id="id_name">
      </div>
      <div class="mb-3">
        <label for="id_email" class="form-label">Ваш Email:</label>
        <input type="email" class="form-control" name="email" required id="id_email">
      </div>
      <div class="mb-3">
        <label for="id_to" class="form-label">Email получателя:</label>
        <input type="email" class="form-control" name="to" required id="id_to">
      </div>
      <div class="mb-3">
        <label for="id_comments" class="form-label">Comments:</label>
        <textarea name="comments" class="form-control" cols="40" rows="10" id="id_comments"></textarea>
      </div>
      {% csrf_token %}  
      <p>
        <input type="submit" value="Отправить" class="btn btn-outline-success">
      </p>   
    </form>  
  {% endif %}  
{% endblock %}