Pet_Project/myblog/blog/urls.py
from django.urls import path  
from . import views  
  
app_name = 'blog'  
  
urlpatterns = [    
    path('', views.post_list, name='post_list'), 
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'), 
    path('search/', views.post_search, name='post_search'),
]

Pet_Project/myblog/myblog/urls.py
from django.urls import path, include  
from django.contrib import admin  
  
  
urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('blog/', include('blog.urls', namespace='blog')), 
    path('user/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls')), 
]

Pet_Project/myblog/user/urls.py
from django.urls import path

from . import views


app_name = 'user'
urlpatterns = [
    path('login_user', views.login_user, name='login'),
    path('logout_user', views.logout_user, name='logout'),
    path('register_user', views.register_user, name='register_user'),
]

Pet_Project/myblog/blog/models.py
from django.db import models 
from django.utils import timezone 
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):  
    def get_queryset(self):  
        return super(PublishedManager,self).get_queryset().filter(status='published')

class Post(models.Model): 
    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'),) 
    title = models.CharField(max_length=250) 
    slug = models.SlugField(max_length=250, unique_for_date='publish') 
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts') 
    body = models.TextField() 
    publish = models.DateTimeField(default=timezone.now) 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft') 
    objects = models.Manager()    
    published = PublishedManager()
    tags = TaggableManager()

    class Meta: 
        ordering = ('-publish',) 

    def __str__(self): 
        return self.title
    
    def get_absolute_url(self):  
        return reverse('blog:post_detail',  
		       args=[self.publish.year,  
		       self.publish.month,  
		       self.publish.day,  
		       self.slug])
    
class Comment(models.Model):  
    post = models.ForeignKey(Post,  
			     on_delete=models.CASCADE,  
			     related_name='comments')  
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE, related_name='users')
    body = models.TextField()  
    created = models.DateTimeField(auto_now_add=True)  
    updated = models.DateTimeField(auto_now=True)  
    active = models.BooleanField(default=True)  
      
    class Meta:  
        ordering = ('created',)  
          
    def __str__(self):  
        return 'Comment by {} on {}'.format(self.user, self.post)

Pet_Project/myblog/blog/forms.py
from django import forms  
from .models import Comment
  
  
class EmailPostForm(forms.Form):  
    name = forms.CharField(max_length=25)  
    email = forms.EmailField()  
    to = forms.EmailField()  
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):  
    class Meta:  
        model = Comment  
        fields = ('body',)
        labels = {
            'body': '',
        }
class SearchForm(forms.Form): 
    query = forms.CharField()

Pet_Project/myblog/blog/views.py
from django.shortcuts import redirect, render, get_object_or_404 
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count  
from django.core.mail import send_mail 
from .forms import EmailPostForm, CommentForm, SearchForm 
from .models import Post, Comment
from taggit.models import Tag 
from django.contrib.postgres.search import SearchVector 

def post_list(request, tag_slug=None):  
    object_list = Post.published.all()  
    tag = None  
  
    if tag_slug:  
        tag = get_object_or_404(Tag, slug=tag_slug)  
        object_list = object_list.filter(tags__in=[tag])  
  
    paginator = Paginator(object_list, 4)  # 3 поста на каждой странице  
    page = request.GET.get('page')  
    try:  
        posts = paginator.page(page)  
    except PageNotAnInteger:  
        # Если страница не является целым числом, поставим первую страницу  
        posts = paginator.page(1)  
    except EmptyPage:  
        # Если страница больше максимальной, доставить последнюю страницу результатов  
        posts = paginator.page(paginator.num_pages)  
    return render(request,'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})

def post_detail(request, year, month, day, post):  
    post = get_object_or_404(Post, slug=post,  
				   status='published',  
				   publish__year=year,  
				   publish__month=month,  
				   publish__day=day)  
      
    # Список активных комментариев к этой записи  
    comments = post.comments.filter(active=True)  
    new_comment = None  
    if request.method == 'POST':
        # Комментарий был опубликован
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            # Создайте объект Comment, но пока не сохраняйте в базу данных
            new_comment = comment_form.save(commit=False)
            # Назначить текущий пост комментарию
            new_comment.post = post
            new_comment.user = request.user
             # Сохранить комментарий в базе данных
            new_comment.save()
            return redirect(request.path)
    else:  
        comment_form = CommentForm() 
    post_tags_ids = post.tags.values_list('id', flat=True)  
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)  
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4] 
    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form, 'similar_posts': similar_posts})

def post_share(request, post_id):   
    # Получить пост по id   
    post = get_object_or_404(Post, id=post_id, status='published')   
    sent = False   
    if request.method == 'POST':   
        # Форма была отправлена   
        form = EmailPostForm(request.POST)   
        if form.is_valid():
            # Поля формы прошли проверку
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading " {}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True     
    else:   
        form = EmailPostForm()   
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

def post_search(request): 
    form = SearchForm() 
    query = None 
    results = [] 
    if 'query' in request.GET: 
        form = SearchForm(request.GET) 
        if form.is_valid(): 
            query = form.cleaned_data['query'] 
            results = Post.objects.annotate(
                search=SearchVector('title', 'body'), 
            ).filter(search=query) 
    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})

Pet_Project/myblog/blog/templates/blog/base.html
{% load blog_tags %}    
<!DOCTYPE html>  
<html lang="ru">  
<head>  
  {% load static %}
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" type="text/css" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">  
</head>
<body>
  <div class="container overflow-hidden">
    <div class="row g-0">
      <div class="shadow-sm mb-2 bg-white rounded">
        <div class="col-12">
          <div class="p-3">
            <div class="row g-0">
              <div class="col-3">
                <div class="p-2">
                  <h3>My blog</h3>
                </div>
              </div>
              <div class="col">
                <div class="p-2">
                  <ul class="nav nav-pills nav-justified">
                    <li class="nav-item">
                      <a class="nav-link"  aria-current="page" href="{% url 'blog:post_search' %}">Поиск</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'blog:post_list' %}">На Главную</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'user:logout' %}">Выйти</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'user:register_user' %}">Регистрация</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'user:login' %}">Вход</a>
                    </li>
                    {% endif %}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-8">
        <div class="p-3">
        {% block content %}  
        {% endblock %}
        </div>
      </div>
      <div class="col-4">
        <div class="p-3">
        <p>В данном блоге вы можете найти {% total_posts %} интересных для прочтения постов.</p>  
        <h3>Последние посты</h3>  
        {% show_latest_posts 3 %}
        <h3>Самые комментируемые посты</h3>  
        {% get_most_commented_posts as most_commented_posts %} 
        {% for post in most_commented_posts %} 
        <div class="list-group">
          <a href="{{ post.get_absolute_url }}" class="list-group-item list-group-item-action">{{ post.title }}</a>
        </div>
        {% endfor %}
        </div>
      </div>
    </div>
  </div> 
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>  
</html>

Pet_Project/myblog/blog/templates/blog/pagination.html
<div class="pagination">  
    <span class="step-links">  
     {% if page.has_previous %}  
         <a href="?page={{ page.previous_page_number }}">Предыдущая</a>  
     {% endif %}  
       <span class="current">  
     Страница {{ page.number }} из {{ page.paginator.num_pages }}.  
       </span>  
     {% if page.has_next %}  
        <a href="?page={{ page.next_page_number }}">Следующая</a>  
     {% endif %}  
     </span>  
   </div>